@echo off
ECHO creating build/test.o ...
g++ -c src/test.cpp -I./include -o build/test.o
ECHO creating build/iterator.o ... 
g++ -c src/iterator.cpp -I./include -o build/iterator.o
ECHO creating build/linked_list.o ...
g++ -c src/linked_list.cpp -I./include -o build/linked_list.o